
target_compile_definitions(${FIRMWARE} PRIVATE
	MIPI_DISPLAY_PIN_CS=21
	MIPI_DISPLAY_PIN_DC=17
	MIPI_DISPLAY_PIN_RST=20
	MIPI_DISPLAY_PIN_BL=16
	MIPI_DISPLAY_PIN_CLK=18
	MIPI_DISPLAY_PIN_MOSI=19
	MIPI_DISPLAY_PIN_MISO=-1
	MIPI_DISPLAY_SPI_PORT=spi0
	MIPI_DISPLAY_SPI_CLOCK_SPEED_HZ=68000000
	MIPI_DISPLAY_PIXEL_FORMAT=MIPI_DCS_PIXEL_FORMAT_16BIT
	MIPI_DISPLAY_ADDRESS_MODE=MIPI_DCS_ADDRESS_MODE_MIRROR_X|MIPI_DCS_ADDRESS_MODE_SWAP_XY
	MIPI_DISPLAY_WIDTH=320
	MIPI_DISPLAY_HEIGHT=240
	MIPI_DISPLAY_OFFSET_X=0
	MIPI_DISPLAY_OFFSET_Y=0
	MIPI_DISPLAY_INVERT=1
)
